# Generated by Django 4.1.6 on 2023-02-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=500)),
                ('weight', models.IntegerField()),
                ('cat', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
