# Generated by Django 4.1.6 on 2023-04-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.IntegerField(verbose_name='User Age'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Full Body'), (2, 'Abs Fitness'), (3, 'Belly Fat')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fullname',
            field=models.CharField(max_length=50, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(max_length=500, verbose_name='User Gender'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='weight',
            field=models.IntegerField(verbose_name='User Weight'),
        ),
    ]
