# Generated by Django 4.1.6 on 2023-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfapp', '0002_product_alter_post_age_alter_post_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
