# Generated by Django 4.1.6 on 2023-04-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfapp', '0003_post_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
